name: "Code check"

on:
  workflow_call:

  pull_request:
    paths:
      - "src/**"
      - "tests/**"
      - "composer.json"
      - "ecs.php"
      - "rector.php"
      - "phpstan.neon"
      - "phpstan-baseline.neon"
      - "phpunit.xml"
      - "artisan"

concurrency:
  group: larastrict-check-${{ github.ref }}
  cancel-in-progress: true

jobs:

  code_l10:
    name: "Code check - Laravel 10"
    strategy:
      matrix:
        phpVersion: [ "8.1", "8.2", "8.3" ]
    uses: wrk-flow/reusable-workflows/.github/workflows/php-check.yml@09ffc469f54061cac1e9cebab2c5896676852b5d
    with:
      composerRequireDev: "laravel/framework:^10"
      phpVersion: "${{ matrix.phpVersion }}"
    secrets: inherit

  code_l11:
    name: "Code check - Laravel 11"
    strategy:
      matrix:
        phpVersion: [ "8.2", "8.3" ]
    uses: wrk-flow/reusable-workflows/.github/workflows/php-check.yml@09ffc469f54061cac1e9cebab2c5896676852b5d
    with:
      composerRequireDev: "laravel/framework:^11"
      phpVersion: "${{ matrix.phpVersion }}"
    secrets: inherit

  tests_l9:
    name: "Tests - Laravel 9"
    strategy:
      matrix:
        phpVersion: [ "8.1", "8.2", "8.3" ]
    uses: wrk-flow/reusable-workflows/.github/workflows/php-tests.yml@09ffc469f54061cac1e9cebab2c5896676852b5d
    with:
      composerRequireDev: "laravel/framework:^9"
      phpVersion: "${{ matrix.phpVersion }}"
    secrets: inherit

  tests_l10:
    name: "Tests - Laravel 10"
    strategy:
      matrix:
        phpVersion: [ "8.1", "8.2", "8.3" ]
    uses: wrk-flow/reusable-workflows/.github/workflows/php-tests.yml@09ffc469f54061cac1e9cebab2c5896676852b5d
    with:
      composerRequireDev: "laravel/framework:^10"
      phpVersion: "${{ matrix.phpVersion }}"
    secrets: inherit

  tests_l11:
    name: "Tests - Laravel 11"
    strategy:
      matrix:
        phpVersion: [ "8.2", "8.3" ]
    uses: wrk-flow/reusable-workflows/.github/workflows/php-tests.yml@09ffc469f54061cac1e9cebab2c5896676852b5d
    with:
      composerRequireDev: "laravel/framework:^11"
      phpVersion: "${{ matrix.phpVersion }}"
      gistID: ${{ vars.GIST_ID }}
      gistOnPhpVersion: "8.2"
    secrets: inherit


