name: "Code check"

on:
  workflow_call:

  pull_request:
    paths:
      - "src/**"
      - "tests/**"
      - "composer.json"
      - "ecs.php"
      - "rector.php"
      - "phpstan.neon"
      - "phpstan-baseline.neon"
      - "phpunit.xml"
      - "artisan"

concurrency:
  group: larastrict-check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code:
    name: "Code check"
    uses: wrk-flow/reusable-workflows/.github/workflows/php-check.yml@7562253bdc3769847417e3476b501e7126f5d2c0
    secrets: inherit

  tests:
    name: "Run tests"
    strategy:
      matrix:
        phpVersion: [ "8.1", "8.2", "8.3" ]
    uses: wrk-flow/reusable-workflows/.github/workflows/php-tests.yml@7562253bdc3769847417e3476b501e7126f5d2c0
    with:
      gistID: ${{ vars.GIST_ID }}
      gistOnPhpVersion: "8.2"
      phpVersion: "${{ matrix.phpVersion }}"
    secrets: inherit

