name: "Code check"

on:
  workflow_call:

  pull_request:
    paths:
      - "src/**"
      - "tests/**"
      - "composer.json"
      - "ecs.php"
      - "rector.php"
      - "phpstan.neon"
      - "phpstan-baseline.neon"
      - "phpunit.xml"
      - "artisan"

concurrency:
  group: larastrict-check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code_l9:
    name: "Code check - Laravel 9"
    strategy:
      matrix:
        phpVersion: [ "8.1", "8.2", "8.3" ]
    uses: wrk-flow/reusable-workflows/.github/workflows/php-check.yml@2bfd2e2fdf3fa3cf0cdf1b2c6d0379f91066084e
    with:
      composerRequireDev: "orchestra/testbench:^v7"
      phpVersion: "${{ matrix.phpVersion }}"
    secrets: inherit

  code_l10:
    name: "Code check - Laravel 10"
    strategy:
      matrix:
        phpVersion: [ "8.1", "8.2", "8.3" ]
    uses: wrk-flow/reusable-workflows/.github/workflows/php-check.yml@2bfd2e2fdf3fa3cf0cdf1b2c6d0379f91066084e
    with:
      composerRequireDev: "orchestra/testbench:^v8"
      phpVersion: "${{ matrix.phpVersion }}"
    secrets: inherit

  code_l11:
    name: "Code check - Laravel 11"
    strategy:
      matrix:
        phpVersion: [ "8.2", "8.3" ]
    uses: wrk-flow/reusable-workflows/.github/workflows/php-check.yml@2bfd2e2fdf3fa3cf0cdf1b2c6d0379f91066084e
    with:
      composerRequireDev: "orchestra/testbench:^v9"
      phpVersion: "${{ matrix.phpVersion }}"
    secrets: inherit

  tests_l9:
    name: "Code check - Laravel 9"
    strategy:
      matrix:
        phpVersion: [ "8.1", "8.2", "8.3" ]
    uses: wrk-flow/reusable-workflows/.github/workflows/php-tests.yml@2bfd2e2fdf3fa3cf0cdf1b2c6d0379f91066084e
    with:
      composerRequireDev: "orchestra/testbench:^v7"
      phpVersion: "${{ matrix.phpVersion }}"
    secrets: inherit

  tests_l10:
    name: "Code check - Laravel 10"
    strategy:
      matrix:
        phpVersion: [ "8.1", "8.2", "8.3" ]
    uses: wrk-flow/reusable-workflows/.github/workflows/php-tests.yml@2bfd2e2fdf3fa3cf0cdf1b2c6d0379f91066084e
    with:
      composerRequireDev: "orchestra/testbench:^v8"
      phpVersion: "${{ matrix.phpVersion }}"
    secrets: inherit

  tests_l11:
    name: "Code check - Laravel 11"
    strategy:
      matrix:
        phpVersion: [ "8.2", "8.3" ]
    uses: wrk-flow/reusable-workflows/.github/workflows/php-tests.yml@2bfd2e2fdf3fa3cf0cdf1b2c6d0379f91066084e
    with:
      composerRequireDev: "orchestra/testbench:^v9"
      phpVersion: "${{ matrix.phpVersion }}"
      gistID: ${{ vars.GIST_ID }}
      gistOnPhpVersion: "8.2"
    secrets: inherit


