name: Release
on:
  push:
    branches:
      - "main"

concurrency:
  group: larastrict-release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  commits:
    name: Check commits
    secrets: inherit
    uses: ./.github/workflows/commits.yml

  check:
    name: Check code
    secrets: inherit
    uses: ./.github/workflows/check-code.yml

  deploy:
    needs:
      - check
    name: Create release if changelog has changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.62.0
        id: version
        env:
          DEFAULT_BUMP: patch
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          INITIAL_VERSION: 0.0.1
          TAG_CONTEXT: branch

      - name: Try to update CHANGELOG
        id: changelog
        uses: Requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ steps.version.outputs.new_tag }}

      - name: Create Release
        if: steps.changelog.outputs.changes != ''
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: false
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ github.token }}
          name: ${{ steps.version.outputs.new_tag }}
          tag: ${{ steps.version.outputs.new_tag }}

      - name: Commit CHANGELOG.md
        if: steps.changelog.outputs.changes != ''
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
          file_pattern: CHANGELOG.md

      - name: Remove tag
        if: steps.changelog.outputs.changes == ''
        run: |
          git tag -d ${{ steps.version.outputs.new_tag }}
          git push --delete origin ${{ steps.version.outputs.new_tag }}

  documentation:
    name: Deploy documentation
    needs:
      - deploy
    uses: wrk-flow/reusable-workflows/.github/workflows/deploy-docs.yml@main
    secrets: inherit
